// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quizzes.Data;

namespace Quizzes.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20191225124506_AddTimeTest")]
    partial class AddTimeTest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Quizzes.Data.Model.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Quizzes.Data.Model.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("QuestionId");

                    b.Property<bool>("Selected");

                    b.Property<string>("Text");

                    b.Property<bool>("True");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Quizzes.Data.Model.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDel");

                    b.Property<int>("TestId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Quizzes.Data.Model.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnswerId");

                    b.Property<int>("UrlTestAttendId");

                    b.Property<string>("UrlTestUrl");

                    b.HasKey("Id");

                    b.HasIndex("UrlTestAttendId");

                    b.HasIndex("UrlTestUrl");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Quizzes.Data.Model.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDel");

                    b.Property<string>("Name");

                    b.Property<TimeSpan>("TestTime");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("Quizzes.Data.Model.UrlTest", b =>
                {
                    b.Property<string>("Url")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("NumberOfRuns");

                    b.Property<int>("TestId");

                    b.Property<DateTime>("Time");

                    b.HasKey("Url");

                    b.HasIndex("TestId");

                    b.ToTable("UrlTests");
                });

            modelBuilder.Entity("Quizzes.Data.Model.UrlTestAttend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NumberOfRun");

                    b.Property<int>("Point");

                    b.Property<DateTime>("StartTimeTest");

                    b.Property<TimeSpan>("TestTime");

                    b.Property<string>("UrlTestUrl");

                    b.HasKey("Id");

                    b.HasIndex("UrlTestUrl");

                    b.ToTable("UrlTestAttends");
                });

            modelBuilder.Entity("Quizzes.Data.Model.Answer", b =>
                {
                    b.HasOne("Quizzes.Data.Model.Question", "Question")
                        .WithMany("Replies")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Quizzes.Data.Model.Question", b =>
                {
                    b.HasOne("Quizzes.Data.Model.Test", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Quizzes.Data.Model.Result", b =>
                {
                    b.HasOne("Quizzes.Data.Model.UrlTestAttend")
                        .WithMany("Results")
                        .HasForeignKey("UrlTestAttendId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Quizzes.Data.Model.UrlTest", "UrlTest")
                        .WithMany()
                        .HasForeignKey("UrlTestUrl");
                });

            modelBuilder.Entity("Quizzes.Data.Model.UrlTest", b =>
                {
                    b.HasOne("Quizzes.Data.Model.Test", "Test")
                        .WithMany("UrlTests")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Quizzes.Data.Model.UrlTestAttend", b =>
                {
                    b.HasOne("Quizzes.Data.Model.UrlTest", "UrlTest")
                        .WithMany("UrlTestAttends")
                        .HasForeignKey("UrlTestUrl");
                });
#pragma warning restore 612, 618
        }
    }
}
